server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://ec2-23-20-140-229.compute-1.amazonaws.com:5432/d2dbcvr0d0old9
    username: xkxuqugreeuhfi
    password: 79e178f35f1efdf49a1902d895ad6bfad885f75666fb68a8362526bef87abd9b
  jpa:
    hibernate:
      ddl-auto: update
#              ddl-auto: create
    show-sql: true
    open-in-view: true
    properties:
        hibernate:
          enable_lazy_load_no_trans: true
  sql:
    init:
#      mode: always
      mode: never
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  secret-key: nimakerakshusuzjasndjandoasndasndiasndasndkasndkasdnsaldlaskdn
  expire:
    access_token: 604800000
    refresh_token: 1728000000

verification-code:
    expire-time: 10800000
    limit: 5


twilio:
    account_sid: AC589862161b8d192a992c556b7a9ebd6f
    auth_token: a2fbdc642226401b743cfcdde18e9beb
    phone_number: +16294654158
