server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://152.70.172.194:5432/postgres
    username: postgres
    password: B5fujoOF&PME
  jpa:
    hibernate:
      ddl-auto: update
#              ddl-auto: create
    show-sql: true
    open-in-view: true
    properties:
        hibernate:
          enable_lazy_load_no_trans: true
  sql:
    init:
#      mode: always
      mode: never
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  secret-key: nimakesadjahdjkashdjkashjaherhewkrhwerakshusuzjasndjandoasndasndiasndasndkasndkasdnsaldlaskdn
  expire:
    access_token: 604800000
    refresh_token: 1728000000

verification-code:
    expire-time: 10800000
    limit: 5


twilio:
    account_sid: AC589862161b8d192a992c556b7a9ebd6f
    auth_token: a2fbdc642226401b743cfcdde18e9beb
    phone_number: +16294654158
